### ISSUE TITLE
Datastore memory exception issue

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#221]
When running A LOT of workflows concurrently, this issue arises from the database, turning in. Suspecting it's from transactions not being closed.

```
[datastore] Dec 26, 2020 11:25:58 AM io.grpc.internal.SerializingExecutor run
[datastore] SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@f12b1ce
[datastore] java.lang.IllegalArgumentException: Self-suppression not permitted
[datastore] 	at java.lang.Throwable.addSuppressed(Throwable.java:1072)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$Profile.takeSnapshot(BaseLocalDatastore.java:1568)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$Profile.access$800(BaseLocalDatastore.java:1319)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore$Profile$EntityGroup.incrementVersion(BaseLocalDatastore.java:1364)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore.commitImpl(BaseLocalDatastore.java:1178)
[datastore] 	at com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub.commitImpl(LocalDatastoreFileStub.java:1703)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore.attemptCommit(BaseLocalDatastore.java:1127)
[datastore] 	at com.google.cloud.datastore.emulator.impl.BaseLocalDatastore.commit(BaseLocalDatastore.java:1106)
[datastore] 	at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.commitMutations(CloudDatastoreV1.java:831)
[datastore] 	at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.applyMutationList(CloudDatastoreV1.java:715)
[datastore] 	at com.google.cloud.datastore.emulator.impl.CloudDatastoreV1.commit(CloudDatastoreV1.java:386)
[datastore] 	at com.google.cloud.datastore.emulator.v1.DatastoreV1Emulator.commit(DatastoreV1Emulator.java:97)
[datastore] 	at com.google.cloud.datastore.emulator.v1.DatastoreEmulatorGrpcAdapter$1.commit(DatastoreEmulatorGrpcAdapter.java:147)
[datastore] 	at com.google.datastore.v1.DatastoreGrpc$MethodHandlers.invoke(DatastoreGrpc.java:860)
[datastore] 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:171)
[datastore] 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:283)
[datastore] 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:711)
[datastore] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[datastore] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[datastore] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[datastore] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[datastore] 	at java.lang.Thread.run(Thread.java:748)
[datastore] Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by frikky** [comment]
```
[datastore] Picked up _JAVA_OPTIONS: "-Xmx6g"
```

Seems like it's just a memory issue. Also fixed transaction issues, but it gets slow anyway. By adding the Java options, it can handle way more I assume.

**Comment by frikky** [comment]
Fixed by heavily offloading datastore access to caching. This was simply way too many requests per second (100+)
