### ISSUE TITLE
[BUG] Failing app builds on initial startup

### ISSUE THREAD

**Issue by frikky** [frikky/Shuffle#438]
When starting Shuffle from scratch, some have experienced not being able to start Shuffle at all. 

Docker versions associated:
- Docker version 19.03.11, build 42e35e61f3
- Docker version 19.03.13, build 4484c46d9d

Most of Shuffle has been built on Docker 17.09 originally.

Bug logs seem to indicate it's related to body closing of the image build request
```
shuffle-backend | panic: runtime error: invalid memory address or nil pointer dereference
shuffle-backend | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x127e700]
shuffle-backend | 
shuffle-backend | goroutine 52 [running]:
shuffle-backend | main.buildImageMemory(0x18774c8, 0xc00004a020, 0xc000b3f780, 0x1, 0x1, 0xc0003b5638, 0x16, 0x1, 0x0, 0x0)
shuffle-backend |     /app/docker.go:265 +0x800
shuffle-backend | main.iterateAppGithubFolders(0x18774c8, 0xc00004a020, 0xc000080c00, 0x36, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
shuffle-backend |     /app/walkoff.go:3760 +0x478
shuffle-backend | main.runInitEs(0x1860940, 0xc000042050)
shuffle-backend |     /app/main.go:4132 +0x11e8
shuffle-backend | created by main.initHandlers
shuffle-backend |     /app/main.go:5691 +0x3e05
```

**Comment by frikky** [comment]
Verified that this was a docker version issue. Working on a fix.

**Comment by frikky** [comment]
Bug occurred due to bad DOCKER_API_VERSION specification.
